name: datascience
channels:
- defaults
- conda-forge
dependencies:
- beautifulsoup4=4.5.3
- botocore=1.5.38
- boto=2.46.1
- boto3==1.4.4
- cython=0.26
- ipython=6.1.0
- jinja2=2.9.6
- jsonschema=2.5.1
- jupyter=1.0.0
- libffi=3.2.1
- libgfortran=3.0.0
- libtiff=4.0.6
- libxml2=2.9.2
- matplotlib=2.0.2
- nomkl=1.0
- nose=1.3.7
- numexpr=2.6.2
- numpy=1.13.1
- openblas=0.2.19
- pandas=0.20.3
- patsy=0.4.1
- psycopg2=2.6.2
- pyarrow=0.5.0
- pycrypto=2.6.1
- pytest=3.1.3
- python=3.6.2
- pyyaml=3.12
- requests=2.18.4
- seaborn=0.8
- scipy=0.19.1
- scikit-learn=0.19.0
- statsmodels=0.8.0
- xgboost=0.6a2
- pip:
  - awscli==1.11.75
  - civis==1.6.2
  - civisml-extensions==0.1.5
  - cloudpickle==0.3.1
  - dropbox==7.1.1
  - ftputil==3.3.1
  - glmnet==2.0.0
  - joblib==0.11.0
  - muffnn==1.1.2
  - pubnub==4.0.12
  - pysftp==0.2.9
  - python-simple-hipchat==0.4.0
  - requests-toolbelt==0.8.0
  - tensorflow==1.2.1
  - urllib3==1.22
