name: datascience
channels:
- defaults
- conda-forge
dependencies:
- awscli=1.16.121
- beautifulsoup4=4.7.1
- botocore=1.12.111
- boto=2.49.0
- boto3=1.9.111
- bqplot=0.11.5
- click=6.7
- cloudpickle=0.8.0
- cython=0.29.6
- dask=1.1.4
- feather-format=0.4.0
- ipython=7.3.0
- ipywidgets=7.4.2
- jinja2=2.10
- jsonschema=3.0.1
- jupyter=1.0.0
- libffi=3.2.1
- libgfortran=3.0.0
- libtiff=4.0.10
- libxml2=2.9.8
- matplotlib=3.0.3
- nomkl=1.0
- notebook=5.7.5
- nose=1.3.7
- numexpr=2.6.9
- numpy=1.16.2
- openblas=0.3.6
- pandas=0.24.1
- patsy=0.5.1
- psycopg2=2.7.7
- pyarrow=0.12.1
- pycrypto=2.6.1
- pytest=4.3.0
- python=3.7.1
- pyyaml=3.13
- requests=2.21.0
- s3fs=0.2.0
- seaborn=0.9.0
- scipy=1.2.0
- scikit-learn=0.19.2
- statsmodels=0.9.0
- urllib3=1.24.1
- xgboost=0.81
- pip:
  - civis==1.9.4
  - civisml-extensions==0.1.10
  - dropbox==9.3.0
  - ftputil==3.4
  - glmnet==2.1.1
  - joblib==0.11.0
  - muffnn==2.2.0
  - pubnub==4.1.2
  - pysftp==0.2.9
  - python-simple-hipchat==0.4.0
  - requests-toolbelt==0.9.1
  - tensorflow==1.14.0
